// Auto-generated index of matched Lucide icons
// Source: lucide-icons/ — matched against public/regular/

export const newIcons = [
  // Arrows & Navigation
  "arrow-down",
  "arrow-down-left",
  "arrow-down-right",
  "arrow-down-to-line",
  "arrow-left",
  "arrow-left-right",
  "arrow-right",
  "arrow-up",
  "arrow-up-down",
  "arrow-up-from-line",
  "arrow-up-left",
  "arrow-up-right",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "corner-down-right",
  "move",
  "rotate-ccw",
  "rotate-cw",
  "skip-forward",
  "step-back",
  "unfold-horizontal",
  "unfold-vertical",

  // UI & Layout
  "grid-2x2",
  "grid-3x3",
  "grip-horizontal",
  "grip-vertical",
  "kanban",
  "layout-grid",
  "menu",
  "panel-bottom",
  "panel-left",
  "panel-left-close",
  "panel-right-close",
  "panel-top",

  // Shapes & Indicators
  "circle-alert",
  "circle-check",
  "circle-dot",
  "circle-question-mark",
  "circle-stop",
  "circle-user",
  "circle-x",
  "cross",
  "info",
  "minus",
  "square-arrow-out-up-right",
  "square-arrow-up-right",
  "square-check",
  "square-stop",
  "triangle-alert",

  // Files & Folders
  "file",
  "file-down",
  "file-image",
  "file-lock",
  "file-pen",
  "file-pen-line",
  "file-plus",
  "file-symlink",
  "file-text",
  "folder",
  "folder-closed",
  "folder-input",
  "folder-open",
  "folder-plus",
  "folder-symlink",
  "folder-up",
  "folders",
  "save",

  // Communication
  "mail",
  "mail-check",
  "mail-plus",
  "message-circle",
  "message-circle-warning",
  "message-square",
  "message-square-text",
  "phone",
  "phone-incoming",
  "phone-outgoing",
  "send",

  // Charts & Analytics
  "activity",
  "chart-area",
  "chart-bar",
  "chart-line",
  "chart-pie",
  "trending-up",

  // Commerce & Finance
  "bitcoin",
  "credit-card",
  "dollar-sign",
  "euro",
  "indian-rupee",
  "package",
  "pound-sterling",
  "receipt",
  "shopping-bag",
  "shopping-basket",
  "shopping-cart",
  "truck",
  "wallet",

  // Media & Devices
  "alarm-clock",
  "camera",
  "clapperboard",
  "film",
  "laptop",
  "mic",
  "mic-off",
  "pause",
  "play",
  "tablet",
  "tv",
  "video",
  "volume-1",
  "volume-2",
  "volume-off",
  "watch",

  // Users & Auth
  "contact",
  "lock",
  "lock-open",
  "log-in",
  "log-out",
  "user-cog",
  "user-minus",
  "user-plus",
  "user-round-plus",
  "users",

  // Dev & Tech
  "braces",
  "code",
  "code-xml",
  "columns-3",
  "compass",
  "copy",
  "drafting-compass",
  "git-branch",
  "git-commit-horizontal",
  "layers-2",
  "link",
  "link-2",
  "server",
  "server-cog",
  "terminal",

  // System & Settings
  "archive",
  "bell-off",
  "bookmark",
  "box",
  "calendar",
  "check",
  "clipboard",
  "clipboard-list",
  "clock",
  "clock-alert",
  "ear",
  "eye",
  "eye-closed",
  "eye-off",
  "fingerprint-pattern",
  "flag",
  "flag-triangle-right",
  "funnel",
  "gift",
  "group",
  "hand",
  "heart",
  "history",
  "house",
  "image",
  "image-plus",
  "images",
  "import",
  "inbox",
  "list-filter",
  "map",
  "map-pin",
  "paperclip",
  "pencil",
  "plus",
  "pointer",
  "printer",
  "refresh-cw",
  "repeat",
  "scissors",
  "search",
  "settings",
  "settings-2",
  "share-2",
  "shield",
  "shield-check",
  "shield-x",
  "sliders-horizontal",
  "sliders-vertical",
  "sparkles",
  "star",
  "tag",
  "trash",
  "trash-2",
  "ungroup",

  // Weather & Nature
  "cloud",
  "cloud-download",
  "cloud-rain",
  "cloud-snow",
  "cloud-upload",
  "earth",
  "moon",
  "sun",
  "sunrise",
  "sunset",
  "wind",

  // Misc
  "apple",
  "globe",
  "wifi",
  "wifi-low",
  "x",
  "zap",
] as const;

export type NewIconName = (typeof newIcons)[number];

export const newIconCount = newIcons.length;
