import {
  Heart,
  Home,
  Settings,
  User,
  Mail,
  Phone,
  Calendar,
  Clock,
  Download,
  Upload,
  ChevronRight,
  ChevronLeft,
  Menu,
  Shield,
  Lock,
  Key,
  Zap,
  Award,
  Bell,
  Camera,
  ImageIcon,
  File,
  Folder,
  Tag,
  Bookmark,
  MessageCircle,
  Send,
  Share2,
  ExternalLink,
  Star,
} from "lucide-react";
import { IconData } from "@/lib/types";

export const SAMPLE_ICONS: IconData[] = [
  {
    id: "heart",
    name: "Heart",
    icon: Heart,
    category: "outline",
    tags: ["love", "like", "favorite"],
  },
  {
    id: "home",
    name: "Home",
    icon: Home,
    category: "outline",
    tags: ["house", "main"],
  },
  {
    id: "settings",
    name: "Settings",
    icon: Settings,
    category: "outline",
    tags: ["gear", "config"],
  },
  {
    id: "user",
    name: "User",
    icon: User,
    category: "outline",
    tags: ["person", "profile"],
  },
  {
    id: "mail",
    name: "Mail",
    icon: Mail,
    category: "outline",
    tags: ["email", "message"],
  },
  {
    id: "phone",
    name: "Phone",
    icon: Phone,
    category: "outline",
    tags: ["call", "contact"],
  },
  {
    id: "calendar",
    name: "Calendar",
    icon: Calendar,
    category: "outline",
    tags: ["date", "schedule"],
  },
  {
    id: "clock",
    name: "Clock",
    icon: Clock,
    category: "outline",
    tags: ["time", "watch"],
  },
  {
    id: "download",
    name: "Download",
    icon: Download,
    category: "outline",
    tags: ["save", "arrow"],
  },
  {
    id: "upload",
    name: "Upload",
    icon: Upload,
    category: "outline",
    tags: ["send", "arrow"],
  },
  {
    id: "chevron-right",
    name: "Chevron Right",
    icon: ChevronRight,
    category: "outline",
    tags: ["arrow", "next"],
  },
  {
    id: "chevron-left",
    name: "Chevron Left",
    icon: ChevronLeft,
    category: "outline",
    tags: ["arrow", "back"],
  },
  {
    id: "menu",
    name: "Menu",
    icon: Menu,
    category: "outline",
    tags: ["hamburger", "nav"],
  },
  {
    id: "shield",
    name: "Shield",
    icon: Shield,
    category: "outline",
    tags: ["security", "protect"],
  },
  {
    id: "lock",
    name: "Lock",
    icon: Lock,
    category: "outline",
    tags: ["security", "private"],
  },
  {
    id: "key",
    name: "Key",
    icon: Key,
    category: "outline",
    tags: ["password", "access"],
  },
  {
    id: "zap",
    name: "Zap",
    icon: Zap,
    category: "outline",
    tags: ["lightning", "fast"],
  },
  {
    id: "award",
    name: "Award",
    icon: Award,
    category: "outline",
    tags: ["badge", "winner"],
  },
  {
    id: "bell",
    name: "Bell",
    icon: Bell,
    category: "outline",
    tags: ["notification", "alert"],
  },
  {
    id: "camera",
    name: "Camera",
    icon: Camera,
    category: "outline",
    tags: ["photo", "picture"],
  },
  {
    id: "image",
    name: "Image",
    icon: ImageIcon,
    category: "outline",
    tags: ["photo", "picture"],
  },
  {
    id: "file",
    name: "File",
    icon: File,
    category: "outline",
    tags: ["document", "paper"],
  },
  {
    id: "folder",
    name: "Folder",
    icon: Folder,
    category: "outline",
    tags: ["directory", "files"],
  },
  {
    id: "tag",
    name: "Tag",
    icon: Tag,
    category: "outline",
    tags: ["label", "price"],
  },
  {
    id: "bookmark",
    name: "Bookmark",
    icon: Bookmark,
    category: "outline",
    tags: ["save", "mark"],
  },
  {
    id: "message-circle",
    name: "Message Circle",
    icon: MessageCircle,
    category: "outline",
    tags: ["chat", "comment"],
  },
  {
    id: "send",
    name: "Send",
    icon: Send,
    category: "outline",
    tags: ["mail", "arrow"],
  },
  {
    id: "share-2",
    name: "Share",
    icon: Share2,
    category: "outline",
    tags: ["export", "social"],
  },
  {
    id: "external-link",
    name: "External Link",
    icon: ExternalLink,
    category: "outline",
    tags: ["open", "new"],
  },
  {
    id: "star",
    name: "Star",
    icon: Star,
    category: "filled",
    tags: ["favorite", "rating"],
  },
];
