import { IconData } from "@/lib/types";

export const REAL_ICONS: IconData[] = [
  { id: "accessibility-circle-person", name: "Circle Person", url: "/regular/accessibility/CirclePerson.svg", category: "accessibility", tags: ["accessibility", "person"] },
  { id: "accessibility-ear", name: "Ear", url: "/regular/accessibility/Ear.svg", category: "accessibility", tags: ["accessibility", "hearing"] },
  { id: "accessibility-hand-4-finger", name: "Hand 4 Finger", url: "/regular/accessibility/Hand4Finger.svg", category: "accessibility", tags: ["accessibility", "hand"] },
  { id: "accessibility-pointer", name: "Pointer", url: "/regular/accessibility/Pointer.svg", category: "accessibility", tags: ["accessibility", "mouse", "pointer"] },
  { id: "accessibility-thumbs-down", name: "Thumbs Down", url: "/regular/accessibility/ThumbsDown.svg", category: "accessibility", tags: ["accessibility", "dislike"] },
  { id: "accessibility-thumbs-up", name: "Thumbs Up", url: "/regular/accessibility/ThumbsUp.svg", category: "accessibility", tags: ["accessibility", "like"] },

  { id: "actions-arrow-inbox", name: "Arrow Inbox", url: "/regular/actions/ArrowInbox.svg", category: "action", tags: ["actions", "inbox"] },
  { id: "actions-arrow-out-of-box", name: "Arrow Out Of Box", url: "/regular/actions/ArrowOutOfBox.svg", category: "action", tags: ["actions", "export"] },
  { id: "actions-arrow-redo-down", name: "Arrow Redo Down", url: "/regular/actions/ArrowRedoDown.svg", category: "action", tags: ["actions", "redo"] },
  { id: "actions-arrow-rotate-clockwise", name: "Arrow Rotate Clockwise", url: "/regular/actions/ArrowRotateClockwise.svg", category: "action", tags: ["actions", "rotate"] },
  { id: "actions-arrow-rotate-counter-clockwise", name: "Arrow Rotate Counter Clockwise", url: "/regular/actions/ArrowRotateCounterClockwise.svg", category: "action", tags: ["actions", "rotate"] },
  { id: "actions-arrow-rotate-left-right", name: "Arrow Rotate Left Right", url: "/regular/actions/ArrowRotateLeftRight.svg", category: "action", tags: ["actions", "rotate"] },
  { id: "actions-arrows-repeat-right-left", name: "Arrows Repeat Right Left", url: "/regular/actions/ArrowsRepeatRightLeft.svg", category: "action", tags: ["actions", "repeat"] },
  { id: "actions-chain-link-3", name: "Chain Link 3", url: "/regular/actions/ChainLink3.svg", category: "action", tags: ["actions", "link"] },
  { id: "actions-chain-link-4", name: "Chain Link 4", url: "/regular/actions/ChainLink4.svg", category: "action", tags: ["actions", "link"] },
  { id: "actions-clipboard", name: "Clipboard", url: "/regular/actions/Clipboard.svg", category: "action", tags: ["actions", "copy"] },
  { id: "actions-clipboard-2", name: "Clipboard 2", url: "/regular/actions/Clipboard2.svg", category: "action", tags: ["actions", "copy"] },
  { id: "actions-cloud-download", name: "Cloud Download", url: "/regular/actions/CloudDownload.svg", category: "action", tags: ["actions", "download"] },
  { id: "actions-cloud-upload", name: "Cloud Upload", url: "/regular/actions/CloudUpload.svg", category: "action", tags: ["actions", "upload"] },
  { id: "actions-edit-big", name: "Edit Big", url: "/regular/actions/EditBig.svg", category: "action", tags: ["actions", "edit"] },
  { id: "actions-edit-small-2", name: "Edit Small 2", url: "/regular/actions/EditSmall2.svg", category: "action", tags: ["actions", "edit"] },
  { id: "actions-file-download", name: "File Download", url: "/regular/actions/FileDownload.svg", category: "action", tags: ["actions", "download"] },
  { id: "actions-folder-upload", name: "Folder Upload", url: "/regular/actions/FolderUpload.svg", category: "action", tags: ["actions", "upload"] },
  { id: "actions-import", name: "Import", url: "/regular/actions/Import.svg", category: "action", tags: ["actions", "import"] },
  { id: "actions-minus-small", name: "Minus Small", url: "/regular/actions/MinusSmall.svg", category: "action", tags: ["actions", "minus"] },
  { id: "actions-page-edit-text", name: "Page Edit Text", url: "/regular/actions/PageEditText.svg", category: "action", tags: ["actions", "edit"] },
  { id: "actions-pencil", name: "Pencil", url: "/regular/actions/Pencil.svg", category: "action", tags: ["actions", "edit"] },
  { id: "actions-printer", name: "Printer", url: "/regular/actions/Printer.svg", category: "action", tags: ["actions", "print"] },
  { id: "actions-repeat", name: "Repeat", url: "/regular/actions/Repeat.svg", category: "action", tags: ["actions", "repeat"] },
  { id: "actions-scissors-2", name: "Scissors 2", url: "/regular/actions/Scissors2.svg", category: "action", tags: ["actions", "cut"] },
  { id: "actions-share-arrow-down", name: "Share Arrow Down", url: "/regular/actions/ShareArrowDown.svg", category: "action", tags: ["actions", "share"] },
  { id: "actions-square-arrow-top-right", name: "Square Arrow Top Right", url: "/regular/actions/SquareArrowTopRight.svg", category: "action", tags: ["actions", "share"] },
  { id: "actions-square-arrow-top-right-2", name: "Square Arrow Top Right 2", url: "/regular/actions/SquareArrowTopRight2.svg", category: "action", tags: ["actions", "share"] },
  { id: "actions-square-behind-square-2", name: "Square Behind Square 2", url: "/regular/actions/SquareBehindSquare2.svg", category: "action", tags: ["actions", "copy"] },
  { id: "actions-square-behind-square-4", name: "Square Behind Square 4", url: "/regular/actions/SquareBehindSquare4.svg", category: "action", tags: ["actions", "copy"] },
  { id: "actions-step-back", name: "Step Back", url: "/regular/actions/StepBack.svg", category: "action", tags: ["actions", "undo"] },
  { id: "actions-trash-can", name: "Trash Can", url: "/regular/actions/TrashCan.svg", category: "action", tags: ["actions", "delete"] },
  { id: "actions-trash-can-simple", name: "Trash Can Simple", url: "/regular/actions/TrashCanSimple.svg", category: "action", tags: ["actions", "delete"] },
  { id: "actions-trash-permanently", name: "Trash Permanently", url: "/regular/actions/TrashPermanently.svg", category: "action", tags: ["actions", "delete"] },
  { id: "actions-floppy-disk-save", name: "Floppy Disk Save", url: "/regular/actions/floppy-disk-save.svg", category: "action", tags: ["actions", "save"] },
  { id: "actions-plus", name: "Plus", url: "/regular/actions/plus.svg", category: "action", tags: ["actions", "add"] },
  { id: "actions-refresh", name: "Refresh", url: "/regular/actions/refresh.svg", category: "action", tags: ["actions", "reload"] },

  { id: "brands-apple", name: "Apple", url: "/regular/brands-social-media/Apple.svg", category: "brand", tags: ["brands", "apple"] },
  { id: "brands-chrome", name: "Chrome", url: "/regular/brands-social-media/Chrome.svg", category: "brand", tags: ["brands", "chrome"] },
  { id: "brands-discord", name: "Discord", url: "/regular/brands-social-media/Discord.svg", category: "brand", tags: ["brands", "discord"] },
  { id: "brands-dribbble", name: "Dribbble", url: "/regular/brands-social-media/Dribbble.svg", category: "brand", tags: ["brands", "dribbble"] },
  { id: "brands-facebook", name: "Facebook", url: "/regular/brands-social-media/Facebook.svg", category: "brand", tags: ["brands", "facebook"] },
  { id: "brands-figma", name: "Figma", url: "/regular/brands-social-media/FigmaSimple.svg", category: "brand", tags: ["brands", "figma"] },
  { id: "brands-git", name: "Git", url: "/regular/brands-social-media/Git.svg", category: "brand", tags: ["brands", "git"] },
  { id: "brands-github", name: "Github", url: "/regular/brands-social-media/Github.svg", category: "brand", tags: ["brands", "github"] },
  { id: "brands-google-play", name: "Google Play Store", url: "/regular/brands-social-media/GooglePlayStore.svg", category: "brand", tags: ["brands", "google", "play"] },
  { id: "brands-instagram", name: "Instagram", url: "/regular/brands-social-media/Instagram.svg", category: "brand", tags: ["brands", "instagram"] },
  { id: "brands-linkedin", name: "Linkedin", url: "/regular/brands-social-media/Linkedin.svg", category: "brand", tags: ["brands", "linkedin"] },
  { id: "brands-medium", name: "Medium", url: "/regular/brands-social-media/Medium.svg", category: "brand", tags: ["brands", "medium"] },
  { id: "brands-copilot", name: "Microsoft Copilot", url: "/regular/brands-social-media/MicrosoftCopilot.svg", category: "brand", tags: ["brands", "microsoft", "copilot"] },
  { id: "brands-notion", name: "Notion", url: "/regular/brands-social-media/Notion.svg", category: "brand", tags: ["brands", "notion"] },
  { id: "brands-pinterest", name: "Pinterest", url: "/regular/brands-social-media/Pinterest.svg", category: "brand", tags: ["brands", "pinterest"] },
  { id: "brands-playstation", name: "Playstation", url: "/regular/brands-social-media/Playstation.svg", category: "brand", tags: ["brands", "playstation"] },
  { id: "brands-reddit", name: "Reddit", url: "/regular/brands-social-media/Reddit.svg", category: "brand", tags: ["brands", "reddit"] },
  { id: "brands-slack", name: "Slack", url: "/regular/brands-social-media/Slack.svg", category: "brand", tags: ["brands", "slack"] },
  { id: "brands-snapchat", name: "Snapchat", url: "/regular/brands-social-media/Snapchat.svg", category: "brand", tags: ["brands", "snapchat"] },
  { id: "brands-telegram", name: "Telegram", url: "/regular/brands-social-media/Telegram.svg", category: "brand", tags: ["brands", "telegram"] },
  { id: "brands-twitch", name: "Twitch", url: "/regular/brands-social-media/Twitch.svg", category: "brand", tags: ["brands", "twitch"] },
  { id: "brands-twitter", name: "Twitter", url: "/regular/brands-social-media/Twitter.svg", category: "brand", tags: ["brands", "twitter"] },
  { id: "brands-whatsapp", name: "Whatsapp", url: "/regular/brands-social-media/Whatsapp.svg", category: "brand", tags: ["brands", "whatsapp"] },
  { id: "brands-x", name: "X", url: "/regular/brands-social-media/X.svg", category: "brand", tags: ["brands", "x"] },
  { id: "brands-xbox", name: "Xbox", url: "/regular/brands-social-media/Xbox.svg", category: "brand", tags: ["brands", "xbox"] },
  { id: "brands-youtube", name: "Youtube", url: "/regular/brands-social-media/Youtube.svg", category: "brand", tags: ["brands", "youtube"] },

  { id: "commerce-3d-package", name: "3D Package", url: "/regular/commerce/3dPackage.svg", category: "commerce", tags: ["commerce", "package"] },
  { id: "commerce-add-to-basket", name: "Add To Basket", url: "/regular/commerce/AddToBasket.svg", category: "commerce", tags: ["commerce", "basket"] },
  { id: "commerce-basket-1", name: "Basket 1", url: "/regular/commerce/Basket1.svg", category: "commerce", tags: ["commerce", "basket"] },
  { id: "commerce-bookmark", name: "Bookmark", url: "/regular/commerce/Bookmark.svg", category: "commerce", tags: ["commerce", "bookmark"] },
  { id: "commerce-credit-card-2", name: "Credit Card 2", url: "/regular/commerce/CreditCard2.svg", category: "commerce", tags: ["commerce", "payment"] },
  { id: "commerce-credit-card-add", name: "Credit Card Add", url: "/regular/commerce/CreditCardAdd.svg", category: "commerce", tags: ["commerce", "payment"] },
  { id: "commerce-crypto-wallet", name: "Crypto Wallet", url: "/regular/commerce/CryptoWallet.svg", category: "commerce", tags: ["commerce", "crypto"] },
  { id: "commerce-fast-shipping", name: "Fast Shipping", url: "/regular/commerce/FastShipping.svg", category: "commerce", tags: ["commerce", "shipping"] },
  { id: "commerce-gift-1", name: "Gift 1", url: "/regular/commerce/Gift1.svg", category: "commerce", tags: ["commerce", "gift"] },
  { id: "commerce-receipt-bill", name: "Receipt Bill", url: "/regular/commerce/ReceiptBill.svg", category: "commerce", tags: ["commerce", "bill"] },
  { id: "commerce-shipping", name: "Shipping", url: "/regular/commerce/Shipping.svg", category: "commerce", tags: ["commerce", "shipping"] },
  { id: "commerce-shopping-bag-1", name: "Shopping Bag 1", url: "/regular/commerce/ShoppingBag1.svg", category: "commerce", tags: ["commerce", "shopping"] },
  { id: "commerce-shopping-bag-2", name: "Shopping Bag 2", url: "/regular/commerce/ShoppingBag2.svg", category: "commerce", tags: ["commerce", "shopping"] },
  { id: "commerce-tag", name: "Tag", url: "/regular/commerce/Tag.svg", category: "commerce", tags: ["commerce", "tag"] },
  { id: "commerce-wallet-1", name: "Wallet 1", url: "/regular/commerce/Wallet1.svg", category: "commerce", tags: ["commerce", "wallet"] },
  { id: "commerce-wallet-4", name: "Wallet 4", url: "/regular/commerce/Wallet4.svg", category: "commerce", tags: ["commerce", "wallet"] },

  { id: "communication-archive-1", name: "Archive 1", url: "/regular/communication/Archive1.svg", category: "communication", tags: ["communication", "archive"] },
  { id: "communication-box-2", name: "Box 2", url: "/regular/communication/Box2.svg", category: "communication", tags: ["communication", "box"] },
  { id: "communication-bubble-2", name: "Bubble 2", url: "/regular/communication/Bubble2.svg", category: "communication", tags: ["communication", "chat"] },
  { id: "communication-bubble-3", name: "Bubble 3", url: "/regular/communication/Bubble3.svg", category: "communication", tags: ["communication", "chat"] },
  { id: "communication-bubble-annotation-3", name: "Bubble Annotation 3", url: "/regular/communication/BubbleAnnotation3.svg", category: "communication", tags: ["communication", "chat"] },
  { id: "communication-call-incoming", name: "Call Incoming", url: "/regular/communication/CallIncoming.svg", category: "communication", tags: ["communication", "call"] },
  { id: "communication-call-outgoing", name: "Call Outgoing", url: "/regular/communication/CallOutgoing.svg", category: "communication", tags: ["communication", "call"] },
  { id: "communication-email-1-sparkle", name: "Email 1 Sparkle", url: "/regular/communication/Email1Sparkle.svg", category: "communication", tags: ["communication", "email"] },
  { id: "communication-email-2", name: "Email 2", url: "/regular/communication/Email2.svg", category: "communication", tags: ["communication", "email"] },
  { id: "communication-email-notification", name: "Email Notification", url: "/regular/communication/EmailNotification.svg", category: "communication", tags: ["communication", "email"] },
  { id: "communication-inbox-empty", name: "Inbox Empty", url: "/regular/communication/InboxEmpty.svg", category: "communication", tags: ["communication", "inbox"] },
  { id: "communication-paper-plane", name: "Paper Plane Top Right", url: "/regular/communication/PaperPlaneTopRight.svg", category: "communication", tags: ["communication", "send"] },
  { id: "communication-send", name: "Send", url: "/regular/communication/Send.svg", category: "communication", tags: ["communication", "send"] },
  { id: "communication-telephone", name: "Telephone", url: "/regular/communication/Telephone.svg", category: "communication", tags: ["communication", "call"] },

  { id: "dev-branch", name: "Branch", url: "/regular/dev-tech/Branch.svg", category: "dev", tags: ["dev", "git"] },
  { id: "dev-code", name: "Code", url: "/regular/dev-tech/Code.svg", category: "dev", tags: ["dev", "code"] },
  { id: "dev-code-brackets", name: "Code Brackets", url: "/regular/dev-tech/CodeBrackets.svg", category: "dev", tags: ["dev", "code"] },
  { id: "dev-code-large", name: "Code Large", url: "/regular/dev-tech/CodeLarge.svg", category: "dev", tags: ["dev", "code"] },
  { id: "dev-commits", name: "Commits", url: "/regular/dev-tech/Commits.svg", category: "dev", tags: ["dev", "git"] },
  { id: "dev-console", name: "Console", url: "/regular/dev-tech/Console.svg", category: "dev", tags: ["dev", "terminal"] },
  { id: "dev-server", name: "Server", url: "/regular/dev-tech/Server.svg", category: "dev", tags: ["dev", "server"] },
  { id: "dev-server-1", name: "Server 1", url: "/regular/dev-tech/Server1.svg", category: "dev", tags: ["dev", "server"] },
  { id: "dev-server-2", name: "Server 2", url: "/regular/dev-tech/Server2.svg", category: "dev", tags: ["dev", "server"] },

  { id: "layout-bento", name: "Bento", url: "/regular/layout-structure/Bento.svg", category: "layout", tags: ["layout", "grid"] },
  { id: "layout-board", name: "Board", url: "/regular/layout-structure/Board.svg", category: "layout", tags: ["layout", "kanban"] },
  { id: "layout-columns-3", name: "Columns 3", url: "/regular/layout-structure/Columns3.svg", category: "layout", tags: ["layout", "columns"] },
  { id: "layout-bottom", name: "Layout Bottom", url: "/regular/layout-structure/LayoutBottom.svg", category: "layout", tags: ["layout", "bottom"] },
  { id: "layout-grid-2", name: "Layout Grid 2", url: "/regular/layout-structure/LayoutGrid2.svg", category: "layout", tags: ["layout", "grid"] },
  { id: "layout-sidebar", name: "Layout Sidebar", url: "/regular/layout-structure/LayoutSidebar.svg", category: "layout", tags: ["layout", "sidebar"] },
  { id: "layout-top", name: "Layout Top", url: "/regular/layout-structure/LayoutTop.svg", category: "layout", tags: ["layout", "top"] },
  { id: "layout-sidebar-left", name: "Sidebar Simple Left", url: "/regular/layout-structure/SidebarSimpleLeftSquare.svg", category: "layout", tags: ["layout", "sidebar"] },
  { id: "layout-sidebar-right", name: "Sidebar Simple Right", url: "/regular/layout-structure/SidebarSimpleRightSquare.svg", category: "layout", tags: ["layout", "sidebar"] },
  { id: "layout-grid-circle", name: "Square Grid Circle", url: "/regular/layout-structure/SquareGridCircle.svg", category: "layout", tags: ["layout", "grid"] },
  { id: "layout-grid-search", name: "Square Grid Magnifying Glass", url: "/regular/layout-structure/SquareGridMagnifyingGlass.svg", category: "layout", tags: ["layout", "search"] },

  { id: "nav-arrow-down", name: "Arrow Down", url: "/regular/navigation/ArrowDown.svg", category: "navigation", tags: ["nav", "arrow"] },
  { id: "nav-arrow-left", name: "Arrow Left", url: "/regular/navigation/ArrowLeft.svg", category: "navigation", tags: ["nav", "arrow"] },
  { id: "nav-arrow-right", name: "Arrow Right", url: "/regular/navigation/ArrowRight.svg", category: "navigation", tags: ["nav", "arrow"] },
  { id: "nav-arrow-up", name: "Arrow Up", url: "/regular/navigation/ArrowUp.svg", category: "navigation", tags: ["nav", "arrow"] },
  { id: "nav-chevron-left", name: "Chevron Left", url: "/regular/navigation/ChevronLeft.svg", category: "navigation", tags: ["nav", "arrow"] },
  { id: "nav-chevron-right", name: "Chevron Right", url: "/regular/navigation/ChevronRight.svg", category: "navigation", tags: ["nav", "arrow"] },
  { id: "nav-magnifying-glass", name: "Magnifying Glass", url: "/regular/navigation/MagnifyingGlass.svg", category: "navigation", tags: ["nav", "search"] },
  { id: "nav-home", name: "Home Round Door", url: "/regular/navigation/home-round-door.svg", category: "navigation", tags: ["nav", "home"] },

  { id: "weather-cloud", name: "Cloud", url: "/regular/weather/Cloud.svg", category: "weather", tags: ["weather", "cloud"] },
  { id: "weather-moon", name: "Moon", url: "/regular/weather/Moon.svg", category: "weather", tags: ["weather", "night"] },
  { id: "weather-rainy", name: "Rainy", url: "/regular/weather/Rainy.svg", category: "weather", tags: ["weather", "rain"] },
  { id: "weather-sun", name: "Sun", url: "/regular/weather/Sun.svg", category: "weather", tags: ["weather", "sunny"] },

  { id: "location-compass-round", name: "Compass Round", url: "/regular/location/CompassRound.svg", category: "location", tags: ["location", "compass"] },
  { id: "location-compass-square", name: "Compass Square", url: "/regular/location/CompassSquare.svg", category: "location", tags: ["location", "compass"] },
  { id: "location-earth", name: "Earth", url: "/regular/location/Earth.svg", category: "location", tags: ["location", "earth"] },
  { id: "location-globe", name: "Globe 2", url: "/regular/location/Globe2.svg", category: "location", tags: ["location", "globe"] },
  { id: "location-map", name: "Map", url: "/regular/location/Map.svg", category: "location", tags: ["location", "map"] },
  { id: "location-pin", name: "Map Pin", url: "/regular/location/MapPin.svg", category: "location", tags: ["location", "pin"] },

  { id: "media-back", name: "Back", url: "/regular/media/Back.svg", category: "media", tags: ["media", "back"] },
  { id: "media-camera-1", name: "Camera 1", url: "/regular/media/Camera1.svg", category: "media", tags: ["media", "camera"] },
  { id: "media-camera-3", name: "Camera 3", url: "/regular/media/Camera3.svg", category: "media", tags: ["media", "camera"] },
  { id: "media-clapboard", name: "Clapboard Wide", url: "/regular/media/ClapboardWide.svg", category: "media", tags: ["media", "video"] },
  { id: "media-images-1", name: "Images 1", url: "/regular/media/Images1.svg", category: "media", tags: ["media", "images"] },
  { id: "media-images-sparkle", name: "Images Sparkle", url: "/regular/media/ImagesSparkle.svg", category: "media", tags: ["media", "images"] },
  { id: "media-microphone", name: "Microphone", url: "/regular/media/Microphone.svg", category: "media", tags: ["media", "audio"] },
  { id: "media-pause", name: "Pause", url: "/regular/media/Pause.svg", category: "media", tags: ["media", "pause"] },
  { id: "media-play", name: "Play", url: "/regular/media/Play.svg", category: "media", tags: ["media", "play"] },
  { id: "media-stop", name: "Stop", url: "/regular/media/Stop.svg", category: "media", tags: ["media", "stop"] },
  { id: "media-volume-full", name: "Volume Full", url: "/regular/media/VolumeFull.svg", category: "media", tags: ["media", "volume"] },

  { id: "system-battery-full", name: "Battery Full", url: "/regular/system/BatteryFull.svg", category: "system", tags: ["system", "battery"] },
  { id: "system-bell-2", name: "Bell 2", url: "/regular/system/Bell2.svg", category: "system", tags: ["system", "bell"] },
  { id: "system-settings-gear-1", name: "Settings Gear 1", url: "/regular/system/SettingsGear1.svg", category: "system", tags: ["system", "settings"] },
  { id: "system-wifi-full", name: "Wifi Full", url: "/regular/system/WifiFull.svg", category: "system", tags: ["system", "wifi"] },

  { id: "time-calendar-5", name: "Calendar 5", url: "/regular/time/Calender5.svg", category: "time", tags: ["time", "calendar"] },
  { id: "time-clock", name: "Clock", url: "/regular/time/Clock.svg", category: "time", tags: ["time", "clock"] },
  { id: "time-history", name: "History", url: "/regular/time/History.svg", category: "time", tags: ["time", "history"] },

  { id: "users-contacts", name: "Contacts", url: "/regular/users-auth/Contacts.svg", category: "users", tags: ["users", "contacts"] },
  { id: "users-people", name: "People", url: "/regular/users-auth/People.svg", category: "users", tags: ["users", "people"] },
  { id: "users-user-add", name: "User Add", url: "/regular/users-auth/UserAdd.svg", category: "users", tags: ["users", "add"] },
  { id: "users-settings", name: "User Settings", url: "/regular/users-auth/UserSettings.svg", category: "users", tags: ["users", "settings"] },
];
